name: CI

on:
  push:
    paths: ["seamless-torus/**", ".github/workflows/ci.yml"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip hatch
        cd seamless-torus
        hatch env create test
    - name: Run pytest
      run: |
        cd seamless-torus
        hatch run test:run
